### ISSUE TITLE
no list of services after clicking on sharetus icon

### ISSUE THREAD

**Issue by danc** [jaywink/sharetus#1]
Hi,
As i mentioned on diaspora, after 0.4.0 on PR1.1, I can access the sahretus icon from the sharing page, but clicking on sharetus simply closes the page and goes back to the browser page ... 
I don't have the services list that you shared on diaspora announcement.
Regards,

**Comment by jaywink** [comment]
Hi Danc,

First question - how did you install Sharetus?
1) Via the browser or
2) via the terminal?

If the second I would say dependencies are missing unless you got them fixed manually. If you are running developer mode please try as root:
apt-get -f install

If it doesn't fix anything, please try the following as user:
/usr/bin/python /opt/sharetus/sharetus.py "http://www.example.com" "Just a title"

You should get some kind of Python error hopefully that would indicate where it crashes.

Also if on developer mode, please check the debug log /tmp/out.txt for anything useful.

If you are not on developer mode I suggest removing the app and trying if reinstall helps, install link here: http://goo.gl/35Rba

Btw, what version are you running, the latest PR1.2? I've had it working on both PR1.1 and PR1.2, haven't tried PR1.0.

If you don't have developer mode active I could patch up a version that logs errors to the userspace so we can see what is happening. Would love to iron out any bugs before I release the next version and submit it to Nokia Store, so thanks for reporting.

Br,
Jason

**Comment by danc** [comment]
Hi Jason,
I installed from the browser,
I am in PR1.1 (made a reinstall in pR1.1, don't remember if the first install was in PR1.0 or not)

apt-get -f install showed there was some libs that could be upgraded (libsocial and libpango).
I upgraded (apt-get upgrade), but this seems was not the problem.

For the rest, I made a screenshot of the command, you'll find it under
http://tintouli.free.fr/sharetus

Regards,
Daniel

**Comment by jaywink** [comment]
Hey Daniel,

I think you're running as root in the picture, try to launch it directly via the command line (/usr/bin/python /opt/sharetus/sharetus.py "http://www.example.com" "Just a title") without going into root with "devel-su" - I get the same error if running as root.

Also check that the file "/tmp/sharetus.debug" is not owned by root and if it is please delete it. Then try to run Sharetus via the Share UI and then check contents of sharetus.debug. Forgot about this file in the previous mail :) I'll remove these temp files once a "final" version is out.

Have you customized the N9 core in some way?

Br,
Jason

**Comment by jaywink** [comment]
Btw I tried with the URL in your image and it works for me so it's not a character encoding issue :P

**Comment by danc** [comment]
Thanks for the feedback

when removed /tmp/sharetus.debug, I'm able to see sharetus UI and share something (https://joindiaspora.com/posts/1479317)
but, the UI still doesn't open when I tap on sharetus icon from the share page

Some more screenshots when the command line is invoked :

http://tintouli.free.fr/sharetus

I've installed some apps, but not specially customized the N9 ...

**Comment by jaywink** [comment]
Hi Daniel,

Unfortunately I couldn't find anything clear so I'm guessing here. It's possible the tag retrieving is throwing an exception. Tags are not retrieved due to aegis settings when launching the app via command line so the fact that it works from the command line seems to indicate the problem could be something like this.

So I've added the missing exception catching, please update to just released 0.5.0 version and see if that helps :)

URL:
https://github.com/jaywink/sharetus/raw/master/dist/sharetus_0.5.0_armel.deb
Same as short URL: http://goo.gl/Atzwo

**Comment by danc** [comment]
Hi Jason,
Don't know i uou had my feedback so here it is again :
It improves since I now have the services list GUI that opens.
But when choosing DIaspora service, the link url is not copied into diaspora from to share it (it is copied when I choose twitter for example).
I'll try to do more tests soon.
Regards,

**Comment by jaywink** [comment]
Hi Daniel,

Good to know the service list now opens. The Diaspora\* issue is on D\* side - the mobile bookmarklet is broken :(

Since the original issue is solved, I'll close this one now. If you find anything else that doesn't work or can think of improvements, please let me know! :) Hoping to implement custom sharing targets soon, just been starved of time to code .. :(
